version: "3"
services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    environment:
      - FLASK_ENV=development
    env_file:
      - .env
    depends_on:
      - db

  db:
    build:
      context: .
      dockerfile: Dockerfile_mysql
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: AccessControl
      MYSQL_USER: user
      MYSQL_PASSWORD: password

volumes:
  db_data: